---
apiVersion: batch/v1
kind: Job
metadata:
  name: 0-wave-10-sleep
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  template:
    spec:
      serviceAccountName: argocd-server
      containers:
        - name: sleep
          image: ubuntu:latest
          command:
            - /bin/sh
            - -c
            - |
              sleep 5
      restartPolicy: Never
  backoffLimit: 1
