---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 10-sync-wave
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: https://github.com/fharper/workshops.git
    path: argocd/sync-waves/registry/10-wave
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
